// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqKxAl_Z0DJxFgUERSkhQjpsIxnZufz9U',
    appId: '1:863381541376:web:6a43dba336043450fb7ee5',
    messagingSenderId: '863381541376',
    projectId: 'almanusulu-3838',
    authDomain: 'almanusulu-3838.firebaseapp.com',
    storageBucket: 'almanusulu-3838.firebasestorage.app',
    measurementId: 'G-KMR04LC0YQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6MYM68YpeEZVhEHsc853K8YSbyycVcMk',
    appId: '1:863381541376:android:fd7ff1e50742092afb7ee5',
    messagingSenderId: '863381541376',
    projectId: 'almanusulu-3838',
    storageBucket: 'almanusulu-3838.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf-T0JeUXcnSAc8eUapTIa-CXjJZL9WvU',
    appId: '1:863381541376:ios:c89724ba5ebfee57fb7ee5',
    messagingSenderId: '863381541376',
    projectId: 'almanusulu-3838',
    storageBucket: 'almanusulu-3838.firebasestorage.app',
    iosBundleId: 'com.vural.almanusulu',
  );
}
